# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('initial_password', models.CharField(max_length=100)),
                ('initial_role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanNum', models.IntegerField(primary_key=True, serialize=False)),
                ('activityDate', models.CharField(max_length=100)),
                ('loanInterestRate', models.CharField(max_length=100)),
                ('totalAmount', models.CharField(max_length=100)),
                ('outstandingAmount', models.CharField(max_length=100)),
                ('issuerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer_multi_view.Issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poolType', models.CharField(max_length=100)),
                ('mortgageInterstRate', models.CharField(max_length=100)),
                ('securityInterestRate', models.CharField(max_length=100)),
                ('IssueDate', models.CharField(max_length=100)),
                ('maturityDate', models.CharField(max_length=100)),
                ('issuerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer_multi_view.Issuer')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='poolId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer_multi_view.Pool'),
        ),
    ]
