# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_multi_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'managed': False},
        ),
    ]
