# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer_multi_view', '0002_auto_20170429_1436'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='issuer',
            table='issuer_multi_view_issuer',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='issuer_multi_view_loan',
        ),
        migrations.AlterModelTable(
            name='pool',
            table='issuer_multi_view_pool',
        ),
    ]
